---
# brew

- name: Install/Upgrade Homebrew packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{ homebrew_packages }}"
  register: brew_result

- name: Make directory for Brew Info
  file: path=brew_info state=directory

- name: Log Brew Info
  shell: |
    brew info {{ item | basename }} > brew_info/{{ item | basename }}
  with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

- name: Initialize mackerel-agent (Set API key)
  shell: mackerel-agent init -apikey={{ mackerel_agent_apikey }} -conf /opt/homebrew/etc/mackerel-agent.conf
  ignore_errors: yes

- name: Copy mac_battery.sh to  /opt/homebrew/var/mackerel-agent/ directory
  copy:
    src: roles/mackerel/templates/mac_battery.sh.j2
    dest: /opt/homebrew/var/mackerel-agent/mac_battery.sh
    owner: sogaoh
    group: admin
    mode: +rx

- name: Append to mackerel-agent.conf
  blockinfile:
    dest: /opt/homebrew/etc/mackerel-agent.conf
    backup: yes
    block: |
      {{ item.content }}
    marker: ""
  with_items:
    - "{{ metrics_battery_remain }}"
  changed_when: true
  notify: "Restart mackerel-agent (Darwin)"

- name: Start mackerel-agent (Darwin)
  command: /opt/homebrew/bin/brew services start mackerel-agent --file /opt/homebrew/opt/mackerel-agent/homebrew.mxcl.mackerel-agent.plist
